Accept SSN as parameter in addition to aktørId
navikt/helse-spade pull request #5
Opened 2019-08-08 09:48 UTC by havstein

Her er forslaget til hvordan Spade kan ta inn fødselsnummer ved henting av behandlinger. Jeg ser jo at det kompliserer appen noe.

2019-08-08 10:25 UTC, davidsteinsland commented
gå heller mot aktørregisteret direkte. her blir sparkel bare enda et ledd

2019-08-08 10:45 UTC, havstein commented
Bare for å være sikker på at vi snakker om det samme; det blir ikke flere kall (ref "enda et ledd"), men kallet gjøres eventuelt fra Spade i stedet for Speil eller saksbehandler-appen.

2019-08-08 10:56 UTC, davidsteinsland commented
derfor jeg sa ledd, for kallkjeden blir lengre. Sparkel gjør heller ikke noe anti corruption her så totalen blir bare at vi legger på enda en konsument på sparkel.

2019-08-08 11:05 UTC, havstein commented
Jeg ser ikke hvordan det blir et ledd mer.

1:
a. Speil henter aktørId fra Sparkel
b. Speil kaller Spade med aktørId
c. Spade henter og returnerer behandlinger fra Kafka

2:
a. Speil kaller Spade med SSN
b. Spade henter aktørId fra Sparkel
c. Spade henter og returnerer behandlinger fra Kafka

Hva er det jeg ikke ser?

2019-08-08 11:08 UTC, davidsteinsland commented
jeg mener at spade hentet aktørid fra aktørregisteret direkte, og ikke sparkel

2019-08-08 11:09 UTC, havstein commented
Ok, da er jeg med, takk 👍

2019-08-28 09:34 UTC, StefanEngelien-Nav requested changes
Jakob og jeg har diskutert denne: Vi har jo et prinsipp om at vi skal oversette fra fnr til aktørId så nært brukeren som mulig, og deretter kun bruke aktørId mellom maskiner. Dette er først og fremst for å sikre brukerens sensitive data litt bedre, siden vi har bedre kontroll på hvem som bruker aktørregisteret enn på fødselsnummer som er jo offentlig tilgjengelig informasjon. Neste fordel er å begrense antall kall til aktørregisteret, da de har svært høy trafikk.

Så er det jo en skjønnsmessig vurdering om det er Speil-backenden eller Spade som er "nærmest mulig brukeren"... Min største innsigelse mot å bruke fnr for å slå opp behandlinger i spade, er at man da knytter fnr og sensitiv informasjon sammen, og siden fnr er path-param, så havner det i access-logger, og så videre.

Vi ble derfor enige om at Speil konverter fnr til aktørId backend, og dette endepunktet forblir som før. Foreslår også at Speil bruker Sparkel sitt fnr-oppslag, så kan vi heller vurdere å legge på caching der for å minimere antall kall mot aktør-registeret. 

For fremtiden hadde det kanskje hadde det vært enda bedre å ha vår egen kafka/push-baserte Aktør-tjeneste, om det ikke er for utopisk.

2019-08-28 09:57 UTC, davidsteinsland commented
Enig i det som skrives, men jeg syns at Speil burde kalle aktørregisteret direkte uten å gå via Sparkel. Sparkel skal bare fungere som et anti corruption layer og er mest rettet mot Spa. Aktørregister-oppslaget i sparkel gjør ingen anti-corruption, og medfører bare et ekstra ledd i nettverkskallet. Jeg har som mål å bli kvitt det oppslaget i Sparkel, og da burde vi holde antall konsumenter til «the bare minimum».

2019-08-28 11:44 UTC, royag-nav commented
Spenn bruker også sparkel for aktør-oppslag 😬  
Burde vi kanskje hatt en egen ren "helse-aktør-service" ?
For det er jo også forsåvidt dumt at sparkel legger til service-brukere i whitelisten som egentlig kun trenger aktør-oppslag, men som jo da også får tilgang på _alt_ sparkel har å tilby.

2019-08-29 08:38 UTC, StefanEngelien-Nav commented
> Enig i det som skrives, men jeg syns at Speil burde kalle aktørregisteret direkte uten å gå via Sparkel. Sparkel skal bare fungere som et anti corruption layer og er mest rettet mot Spa. Aktørregister-oppslaget i sparkel gjør ingen anti-corruption, og medfører bare et ekstra ledd i nettverkskallet. Jeg har som mål å bli kvitt det oppslaget i Sparkel, og da burde vi holde antall konsumenter til «the bare minimum».

Skjønner at det er litt bortkastet å ha det oppslaget i sparkel om det ikke gjøres noe sparkling - men er du med på fordelene med å legge på caching der? På DigiSyfo fikk vi litt kjeft av aktørregisteret fordi vi gjorde så mange kall mot dem - men det var jo fordi vi på helse har en av de største brukergruppene. Man skal ikke drive med premature optimization, men jeg ser det likevel som sannsynlig at Sykepenger kommer til å gjøre enda flere aktøroppslag, og at vi dermed kunne hatt nytte av å ha et felles, cachet endepunkt. Va tycks?

2019-08-29 08:39 UTC, StefanEngelien-Nav commented
> Spenn bruker også sparkel for aktør-oppslag 😬
> Burde vi kanskje hatt en egen ren "helse-aktør-service" ?
> For det er jo også forsåvidt dumt at sparkel legger til service-brukere i whitelisten som egentlig kun trenger aktør-oppslag, men som jo da også får tilgang på _alt_ sparkel har å tilby.

Det er jo også en farbar vei 👍

2019-08-29 08:51 UTC, davidsteinsland commented
Den type caching burde aktørregisteret hatt selv. Det er ikke så mye trafikk at de ikke burde tålt det. Aktørregisteret er veldig enkelt å kalle, ettersom det bare er et rest-api, og derfor tenker jeg at en «helse-aktør-service» også her ville vært unødvendig.

2019-08-29 13:38 UTC, royag-nav commented
Jeg forestiller meg (uten at jeg egentlig vet da;) at det største "aberet" er at vi for hver lille service som trenger aktør-veksling må bestille tilgang for en service-brukeren(?). At helse generelt har tilgang (til en ikke-veeeldig-sensitiv tjeneste) via en helse-service, og at vi vedlikeholder vår egen whitelist innad føles mer agilt :)  Og ang.caching... typisk vil kanskje vi ha flere tjenester på rad og rekke (mottak,spa,spenn++?) som faktisk veksler inn samme person flere ganger på kort tid? Litt helse-lokal caching kan jo være fint da, spesielt hvis ikke aktørregisteret har caching i det hele tatt :)

2019-08-29 14:16 UTC, davidsteinsland commented
Tror ikke servicebrukeren må ha noen spesielle roller for å lese fra aktørregisteret. Caching syns jeg blir litt premature optimization, og på feil sted.

2019-10-03 09:46 UTC, havstein commented
Implementert i Speil, navikt/helse-speil#227

2019-10-03 09:46 UTC, closed without merging